language: php

notifications:
  email:
    recipients:
      - dev@dmk-ebusiness.de
    on_success: change
    on_failure: always

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TYPO3_VERSION="^6.2.14"
    - php: 5.6
      env: TYPO3_VERSION="^7.6.0"
    - php: 7.0
      env: TYPO3_VERSION="^7.6.0"
    - php: 7.0
      env: TYPO3_VERSION="^8.7.0"
    - php: 7.1
      env: TYPO3_VERSION="^7.6.0"
    - php: 7.1
      env: TYPO3_VERSION="^8.7.0"
        - TYPO3_VERSION="^8.7.0"
        - COVERAGE=true

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  - composer require -o digedag/rn-base="dev-master"
  - composer require -o dmk/mkforms="dev-master"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
