language: php

notifications:
    email:
        recipients:
            - dev@dmk-ebusiness.de
        on_success: change
        on_failure: always

matrix:
    fast_finish: true
    include:
        -   php: 7.2
            env:
                - TYPO3_CORE="typo3/minimal=^9.5.0"
                - COVERAGE=true
        -   php: 7.2
            env: TYPO3_CORE="typo3/cms=^8.7.0"
        -   php: 7.2
            env: TYPO3_CORE="typo3/cms=^7.6.0"
        -   php: 7.1
            env: TYPO3_CORE="typo3/cms=^8.7.0"
        -   php: 7.1
            env: TYPO3_CORE="typo3/cms=^7.6.0"
        -   php: 7.0
            env: TYPO3_CORE="typo3/cms=^8.7.0"
        -   php: 7.0
            env: TYPO3_CORE="typo3/cms=^7.6.0"
        -   php: 5.6
            env: TYPO3_CORE="typo3/cms=^7.6.0"

sudo: false

addons:
    apt:
        packages:
            - parallel

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - composer --version

before_script:
    ### first remove the "typo3/cms-core". for typo3 6, 7 and 8 it will be "typo3/cms"
    - composer remove --no-update typo3/cms typo3/cms-core
    - composer require "$TYPO3_CORE"
    ### Restore composer.json
    - git checkout composer.json
    - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
    - >
        echo;
        echo "Running unit tests";
        .Build/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
